### ISSUE TITLE
Bug Report - Google Sheet Sync is not working

### ISSUE THREAD

**Issue by jonathonbyrdziak** [merchantprotocol/theadslab#13]
Issue Brief
--
When was this bug experienced:
What is the purpose of this issue? Explain the background context. Please remember to search the issue tracker for your issue before posting a possible duplicate. It's better to enhance an existing issue with your experience than to create a second issue that will be immediately closed.

After setting up a google sheet sync we have received resolutions, but we have not been seeing identities synced to the google sheet we were provided.

Steps to reproduce
--
Listing of detailed steps needed to reproduce this error. Emphasis any steps that are critical to the reproduction of the bug.
1. Create a google sheet integration and save it
2. You're provided a url to the sheet that will receive identities
3. Make sure your pixel is installed on the clients website and traffic is hitting the pixel

Actual result
--
Explain the unexpected "bug(s)" that we should be looking for.
1. Notice that there are identities found in the Identified Leads area
2. But there are no identities synced into the google sheet

Expected result
--
Explain what you "expect" to be happening instead of the bug.
- [ ] We expect identities to be synced into the google sheet

**Comment by Flywheeltargeting** [comment]
second this bug as my sheets no longer sync

**Comment by jonathonbyrdziak** [comment]
This is a duplicate of an open feature ticket we're developing #5 Google Sheet Integration Sync
