### ISSUE TITLE
Update webhook to allow Bulk Request resolutions to be POSTed to Zapier instead of real time to lower Zap costs.  

### ISSUE THREAD

**Issue by alvindef** [merchantprotocol/theadslab#24]
Feature Brief
--
Explain your idea in detail: I would like to have resolutions delivered all in 1 bulk request instead of individual real time which will drive up the zapier costs

Expectations
--
List the exact expectations that need to be accomplished with this feature:
If we have 50 resolutions in 1 day, I do NOT want to pay for 50 zap costs.  
I prefer to have 1 bulk push of the 50 resolutions by end of day or midnight to the web hook where I can see 50 resolutions in my google spreadsheet.

Resources
--
Attach any screenshots, screencasts, customer information, chat transcripts, emails to support your brief.

**Comment by jonathonbyrdziak** [comment]
The google sheet offers bulk updates while the webhook is specifically for real time.

**Comment by jonathonbyrdziak** [comment]
The webhook is precisely for real time updates, so it will never be a bulk system.

The google sheet is exactly for bulk uploading with no zap costs. Soon, both systems will have the complete data set and you'll be able to choose which route you want to go.
