### ISSUE TITLE
Saving google sheet throws config error

### ISSUE THREAD

**Issue by Flywheeltargeting** [merchantprotocol/theadslab#42]
Issue Brief
error in adding google sheet integration 

When was this bug experienced: 4/22/22

What is the purpose of this issue?  error in adding google sheet integration 

Resources

Steps to reproduce
--
Listing of detailed steps needed to reproduce this error. Emphasis any steps that are critical to the reproduction of the bug.
1. Bug was found on step 2 when saving to create a new goole sheet

Actual result
<img width="1647" alt="Screen Shot 2022-04-22 at 6 14 18 PM" src="https://user-images.githubusercontent.com/102630138/164848164-04b44757-ab5c-429b-90e9-d30557dec6e8.png">

<img width="1647" alt="Screen Shot 2022-04-22 at 6 14 03 PM" src="https://user-images.githubusercontent.com/102630138/164847936-5db895ad-3d76-40f6-a40a-ad40b979012b.png">

**Comment by larissalamaster** [comment]
I keep getting this issue as well!

**Comment by jonathonbyrdziak** [comment]
should be fixed
