### ISSUE TITLE
Site Pixel Installation Issue

### ISSUE THREAD

**Issue by FotorecordPS** [merchantprotocol/theadslab#44]
I have a Wordpress site that I've added the pixel code to in Google Tag Manager from following the instructions from the videos at this link: https://the-ads-lab.circle.so/c/1-access-the-ads-lab/joining-the-ads-lab-dashboard-7c1842

The first problem I encountered was the fact that i had to add a Google Tag Manager code to the website in order for the pixel to register on the Tag Manager side. But after i went back to the AdsLab.io dashboard it wasn't picking up any data. There was mention in the video about giving it a few days but nothing has happened. The dashboard says there is no pixel even though the Tag Manager says otherwise. I've also added the code in the header of the website, in the wordpress HTML code. 

It's been a week and i still have no data coming in from the site, still says there's no tag, etc. It's not connecting. What am i doing wrong?!?
<img width="1581" alt="Screen Shot 2022-05-03 at 1 37 52 PM" src="https://user-images.githubusercontent.com/104857346/166508476-a14b0897-a0e8-478e-9705-7c061a05a2ba.png">
<img width="1462" alt="Screen Shot 2022-05-03 at 1 37 59 PM" src="https://user-images.githubusercontent.com/104857346/166508477-3485a6a5-168f-41ba-a7e0-195e23b0ad41.png">
<img width="1363" alt="Screen Shot 2022-05-03 at 1 38 19 PM" src="https://user-images.githubusercontent.com/104857346/166508479-1a1755df-1e01-4a1a-8ce2-057c575a24ec.png">

**Comment by jonathonbyrdziak** [comment]
Adding our tag manager code to the google tag manager is the incorrect way to implement this pixel.

1. For the simplest implementation please install theadslab javascript tag (not tag manager) directly to the customers website.
1. Load the customers website and "view source" to confirm that the javascript tag is installed.
1. Load the developer toolbar on the customers website and navigate to the "Network" tab to confirm that the pixel is firing without error.
1. View inside the developer console and confirm that the "Pixel" events are logging to the console which will confirm successful installation.

Upon loading and reloading the customers website, a successful installation will begin showing visitors immediately.

**Comment by FotorecordPS** [comment]
1-2. Check. 
3. Pixel Code - Not sure what i'm looking for in Network coding in browser on site to tell me whether it's firing or not. 
4. Negative, it's still not working. It's installed and doesn't show up in dashboard. 
<img width="916" alt="Screen Shot 2022-05-04 at 7 25 41 AM" src="https://user-images.githubusercontent.com/104857346/166672571-47829b02-e674-4890-b73f-5a5f0eaf55ca.png">
<img width="2534" alt="Screen Shot 2022-05-04 at 7 25 57 AM" src="https://user-images.githubusercontent.com/104857346/166672572-1a5b48c2-1221-4390-9828-8ffab4cc0e46.png">
