### ISSUE TITLE
Integration Bug Report - Automobile Ownership

### ISSUE THREAD

**Issue by FotorecordPS** [merchantprotocol/theadslab#46]
Issue Brief
--
When was this bug experienced: When setting up the integration for Google Docs I encountered an error screen.

When trying to create the google doc, the error screen popped up that "aqueous-tesla" doesn't exist in the code. At first i thought it had something to do with my email, so i tried a different email, same result. 

I then thought, well, Tesla's a car, so I omitted the Automobile Ownership Box and it continued to create my google doc. So i'm not collecting auto data, which should be fixed. 

<img width="945" alt="Screen Shot 2022-05-05 at 3 49 54 PM" src="https://user-images.githubusercontent.com/104857346/167014884-8b7f0a87-4fce-4b02-b35a-1867f4be48d2.png">
<img width="1368" alt="Screen Shot 2022-05-05 at 3 50 10 PM" src="https://user-images.githubusercontent.com/104857346/167014885-af9b3108-9190-4fcb-b0ae-85fec3e2c668.png">

**Comment by jonathonbyrdziak** [comment]
Try saving this again, the error should go away. if you encounter the error just try saving once or twice more.
