### ISSUE TITLE
Identified Contacts is blank

### ISSUE THREAD

**Issue by ChristianEscobedo** [merchantprotocol/theadslab#48]
Issue Brief
--
When was this bug experienced: 5/12/22
What is the purpose of this issue? All data disappeared from previous resolutions

Explain the background context.? not sure

 Please remember to search the issue tracker for your issue before posting a possible duplicate. It's better to enhance an existing issue with your experience than to create a second issue that will be immediately closed.

Resources
--
Attach any screenshots, screencasts, customer information, chat transcripts, emails to support the debugging effort.

https://markuphero.com/share/RPTv5NnrVWrB6XEPUFT8

Steps to reproduce
--
Listing of detailed steps needed to reproduce this error. Emphasis any steps that are critical to the reproduction of the bug.
1. Bug was found on `production`
2. ...

Actual result
--
Explain the unexpected "bug(s)" that we should be looking for.
1. ... No data from previous resolutions 

Expected result
--
Explain what you "expect" to be happening instead of the bug.
- [ ] ... Data should not disappear

**Comment by AnnuitiesHQ** [comment]
SAME ISSUE

**Comment by AnnuitiesHQ** [comment]
SAME ISSUE

**Comment by jonathonbyrdziak** [comment]
Yea, I rolled out a unified data table 5/11/2022 to give you more data and more resolutions. That new table isn't compatible with the "identified leads" page at the moment.

Expect this to be updated by friday to provide you with the full data set, including all past data.

**Comment by larissalamaster** [comment]
Sa,e ossie

**Comment by larissalamaster** [comment]
Same issue

**Comment by abadger13** [comment]
same issue

**Comment by abadger13** [comment]
Maybe this means progress? I have site owners asking for leads. This morning on the dashboard the Identified Leads widget gave an error that said 

"Oops… there was a problem during the request. Maybe the server had a temporary issue, or maybe you requested a report with too much data. Please try again. If this error occurs repeatedly please contact your Matomo administrator for assistance.

Need more help? [Community Help](https://forum.matomo.org/)."

Clicking the "contact your Matomo administrator" opened an email to Jonathon, Jesse, and Adam. So I'm reporting here instead.

**Comment by jonathonbyrdziak** [comment]
This should be fixed now. You can see all your data and the calculated match rates now. I'm doing direct queries against the db, so it should be quick too, assuming you dont have TONS of leads.
