### ISSUE TITLE
Google Sheet Integration Sync

### ISSUE THREAD

**Issue by jonathonbyrdziak** [merchantprotocol/theadslab#5]
Integration with Google Sheets. Synchronizing the available dataset with specific tabs within a sheet. Users shall have the ability to sync their resolved leads with google sheets.

- [x] Users will be able to specify the website and the audience to sync to sheets.
- [x] Users will enter the email address to which the synced sheet will be shared with.
- [x] Users can specify what data they would like synced to the sheet
- [x] The system will automatically sync every visitor within the audience with the google sheet.

**Comment by jonathonbyrdziak** [comment]
- [x] Revamped the system to use bulk sync
- [x] Changed the audience from visitor log to pixel fire table
- [x] Added logging throughout the features codebase
- [x] Modified Queue to reset itself in case of a blocking error

**Comment by NellieJor** [comment]
Resolutions not syncing to GS. What should I do to fix this?
