### ISSUE TITLE
Access Denied after setting up google sheet sync

### ISSUE THREAD

**Issue by abadger13** [merchantprotocol/theadslab#50]
Issue Exporting from dashboard to Google Sheet
--

I can see leads and data in the dashboard, but I can't export them. 
I set up export via integration to Google Sheet and when the sheet was generated I clicked the link in the message at the top of the page, and the page said I was denied access. I'm logged in to the right Google account. How do I grab the data? Thanks.

Resources
--

![Screen Shot 2022-05-11 at 12 21 19 PM](https://user-images.githubusercontent.com/43648289/168123756-4e6f859c-8e63-4f27-87b3-c7c042eda6e5.png)
![Screen Shot 2022-05-11 at 12 21 28 PM](https://user-images.githubusercontent.com/43648289/168123760-ebf5f1bd-7e0f-41f9-a79a-b15f854a7036.png)

![Screen Shot 2022-05-12 at 8 39 48 AM](https://user-images.githubusercontent.com/43648289/168123803-137b21fe-529a-42c4-acf9-a8a683f82780.png)

Steps to reproduce
--
1. Set up export in the dashboard via integration tool/tab2. 
2. When I clicked the "Open your google spreadsheet " link I was either denied access or3. 
3. If I wasn't give the "open" link I just got the error message I am showing in this report.

Expected result
--
I should be able to get access to the google sheet.

**Comment by jonathonbyrdziak** [comment]
When creating your sheet integration there's an option to enter your email. Can you provide a screenshot of step 2 of the sheet integration that shows your email entered.

**Comment by abadger13** [comment]
![Screen Shot 2022-05-12 at 12 52 32 PM](https://user-images.githubusercontent.com/43648289/168127990-ea8d230e-99a1-4d20-a05b-be1901a95182.png)

Entering my email fixed the Access Denied.
The resulting Google Sheet is empty but I've been running since May 3, and should have data in the sheet. It's on the dashboard.

**Comment by abadger13** [comment]
Operator error. I forgot about the nul sheet 1. All fixed. Thank you!
