### ISSUE TITLE
Identified Leads not showing, export data seems lite

### ISSUE THREAD

**Issue by abadger13** [merchantprotocol/theadslab#51]
Issue Brief
--
I haven't seen this situation in other reports.

I put the date view on the month of May. Pixel installation was May 3.

We've had 16,491 visits since installation.

13,526 page views.

Today the Identified Leads widget is empty. The widget was showing data in previous days.

The Google Sheet export shows only 6 rows of data, 3 rows of which appear to be 1 unique user.

I'm guessing the empty Identified Leads widget is a bug.

But I was thinking that after 16k site visits we'd see more than 4 leads.

Is there a warm up period or something I don't understand about the ID Graph and how the system reports?

Thank you.

Resources
--
![Screen Shot 2022-05-13 at 7 53 13 AM](https://user-images.githubusercontent.com/43648289/168277808-d5b536dd-d845-4221-8c12-8b9c30ca9e75.png)

Steps to reproduce
--
Screen shot of dashboard, current time/date

Expected result
--
I was seeing leads reported in Identified Leads widget, which is now empty.
I was expecting at least a few hundred identities after over 16k site visitors.

**Comment by jonathonbyrdziak** [comment]
This should be fixed now. You can see all your data and the calculated match rates now. I'm doing direct queries against the db, so it should be quick too, assuming you dont have TONS of leads.
