### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by larissalamaster** [merchantprotocol/theadslab#52]
Not able to see any identified contacts
--
When was this bug experienced: today, previously I've been able to see them 
What is the purpose of this issue? I have been able to see identified visitors before and now they're all gone and the google sheets aren't syncing either
![Screen Shot 2022-05-13 at 2 25 49 PM](https://user-images.githubusercontent.com/105022789/168391601-422476ca-4ed4-4303-86e8-a9a1627cff77.png)

**Comment by abadger13** [comment]
Same issue for me. I understand Jonathon was working on an update that's supposed to address this issue. So I'm waiting for that.

I also have some accounts with really low volumes of traffic, so I'm hoping that the Identified Leads grabs even small leads with little data.

No far not the case with larger volume account.

Looking forward to the update. I can't sell any of these without data. But this will be great with good data.

**Comment by jonathonbyrdziak** [comment]
This should now be working. I've sped it up as much as I can by doing direct queries against the db.

I still need to display OLD contact profiles that were matched previously, but these pages should be displaying and working for you
