### ISSUE TITLE
Google sheets integration not working

### ISSUE THREAD

**Issue by cliffsvr** [merchantprotocol/theadslab#53]
Issue Brief
--
I installed the pixel on two websites. Both have been identifying leads over the last few weeks.

But after I set up the Google sheets webhook through Zapier, neither of them is sending identified leads data to the google sheet.

See screenshot attached.

![Screenshot 2022-05-14 at 16 43 24](https://user-images.githubusercontent.com/102632679/168415009-c9a179ab-b10e-4476-a2e0-2d8f9247245b.png)

I want to make sure before I take any payments that this will work.

Please advise.

**Comment by cliffsvr** [comment]
Here's a quick overview of the problem:
https://www.loom.com/share/02aaac9f39944b378d9d05d122ccedef

**Comment by Flywheeltargeting** [comment]
Also the integration to add a new google sheet is giving an error. 

Way to get the error is add a google sheet integration  the standard way and when you click save on step to it give that error message


<img width="949" alt="Screen Shot 2022-05-14 at 12 53 40 PM" src="https://user-images.githubusercontent.com/102630138/168446436-fca04660-15eb-4494-9eab-74032fefe10f.png">

**Comment by larissalamaster** [comment]
Same issue

**Comment by jonathonbyrdziak** [comment]
@duplicate #54
