### ISSUE TITLE
Bug Report - Limited data points available through Zapier

### ISSUE THREAD

**Issue by cliffsvr** [merchantprotocol/theadslab#57]
Issue Brief
--
I was just trying to set up a new website, but noticed the majority of the datapoints when setting up the webhook through zapier have disapeared.

Including names, emails, sha256, etc.

Screenshot attached.

![Screenshot 2022-05-19 at 15 00 53](https://user-images.githubusercontent.com/102632679/169212206-c833ec4f-99e3-485c-8bd3-c41ab3f84b15.png)

**Comment by jonathonbyrdziak** [comment]
This is fixed
