### ISSUE TITLE
visitor profile Bug Report

### ISSUE THREAD

**Issue by Flywheeltargeting** [merchantprotocol/theadslab#65]
Issue Brief
visitor profile loading is timing out in audiences. this seems to happen on sites that have slightly higher traffic 

 

 

Steps to reproduce
 
Listing of detailed steps needed to reproduce this error. Emphasis any steps that are critical to the reproduction of the bug.
1. set range to year on visitor profile
2. it will return an error and no profiles

**Comment by jonathonbyrdziak** [comment]
fixed it
